# Use a imagem base do MySQL 8.0
FROM mysql:8.0

# Defina as variáveis de ambiente do MySQL
ENV MYSQL_USER=petclinic
ENV MYSQL_PASSWORD=petclinic
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=petclinic
