name: Deploy to AWS ECS

on:
  workflow_call:
    inputs:
      action: 'deploy-aws-ecs'

jobs:
  deploy:
    runs-on: ubuntu-latest

env:
  AWS_REGION: "east-1"
  ECS_CLUSTER_NAME: "petclinic" # Substitua pelo nome do seu cluster ECS
  ECS_SERVICE_NAME: "petclinic2023" # Substitua pelo nome do seu serviço ECS

permissions:
  id-token: write
  contents: read

jobs:
  ECS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::462742955383:role/Github_actions_acess
          role-session-name: samplerolesession
          role-duration-seconds: 900
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and push Docker container
        run: |
          # Replace with your Docker build and push commands
          docker build -t rodrigosousadf/javapet:${{github.run_number}} .
          docker tag rodrigosousadf/javapet:${{github.run_number}}
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker rodrigosousadf/javapet:${{github.run_number}}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER_NAME }} --service ${{ env.ECS_SERVICE_NAME }} --force-new-deployment
