name: Docker

on:
 workflow_call: 

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set DOCKERIMAGE variable
      run: echo "DOCKERIMAGE=rodrigosousadf/javapet:${{github.run_number}}" >> $GITHUB_ENV

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.5.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
       name: Package

    - name: Docker Login
      uses: docker/login-action@v2.1.0 
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKERIMAGE }} # Usamos a variável aqui
