name: Docker

on:
 workflow_call: 

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.5.0
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
       name: Package
       
    - name: Docker Login
      uses: docker/login-action@v2.1.0 
      with:
        username: rodrigosousadf 
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./docker-compose.yml
        push: true
        tags: rodrigosousadf/petclinic:${{github.run_number}}